import { ChevronDown, LogOut, Menu, Radio, RefreshCw, UserCog, Wifi, WifiOff } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import { useRealtime } from '../../context/RealtimeContext'
import { trafficApi } from '../../services/endpoints'
import { formatNumber, timeAgo } from '../../utils/format'
import { riskColor } from '../../utils/theme'
import { ROUTE_META } from './nav'

function useLivePosture() {
  const [posture, setPosture] = useState(null)
  const [updatedAt, setUpdatedAt] = useState(null)

  useEffect(() => {
    let cancelled = false
    const load = async () => {
      try {
        const snapshot = await trafficApi.live({ window: '5m' })
        if (!cancelled) {
          setPosture(snapshot)
          setUpdatedAt(new Date().toISOString())
        }
      } catch {
        /* the topbar indicator is decorative; pages surface real errors */
      }
    }
    load()
    const timer = setInterval(load, 15000)
    return () => {
      cancelled = true
      clearInterval(timer)
    }
  }, [])

  return { posture, updatedAt }
}

export default function Topbar({ onMenu }) {
  const { user, logout } = useAuth()
  const { status, connected, messageCount } = useRealtime()
  const navigate = useNavigate()
  const location = useLocation()
  const { posture, updatedAt } = useLivePosture()
  const [menuOpen, setMenuOpen] = useState(false)
  const menuRef = useRef(null)

  useEffect(() => {
    const onClick = (event) => {
      if (menuRef.current && !menuRef.current.contains(event.target)) setMenuOpen(false)
    }
    document.addEventListener('mousedown', onClick)
    return () => document.removeEventListener('mousedown', onClick)
  }, [])

  const meta = ROUTE_META[location.pathname] || { title: 'CyberForecast AI', subtitle: '' }
  const threatLevel = posture?.threat_level || 'unknown'
  const threatHex = riskColor(threatLevel)
  const simulationActive = Boolean(posture?.simulation?.running)

  return (
    <header className="sticky top-0 z-30 border-b border-slate-800/80 bg-[#080c14]/85 backdrop-blur">
      <div className="flex items-center gap-3 px-3 py-2.5 sm:px-5">
        <button type="button" className="rounded-md p-1.5 text-slate-400 hover:bg-slate-800 hover:text-slate-100 lg:hidden" onClick={onMenu} aria-label="Open navigation">
          <Menu size={17} />
        </button>

        <div className="min-w-0 flex-1">
          <h1 className="truncate text-[15px] font-semibold tracking-tight text-slate-100">{meta.title}</h1>
          <p className="muted hidden truncate sm:block">{meta.subtitle}</p>
        </div>

        <div className="flex items-center gap-2">
          {/* simulation banner - synthetic data must always be identifiable */}
          {simulationActive ? (
            <span
              className="badge hidden border-purple-500/40 bg-purple-500/10 text-purple-300 sm:inline-flex"
              title="Traffic currently being generated by the built-in simulator"
            >
              <Radio size={10} className="animate-pulse" /> Simulation mode
            </span>
          ) : null}

          {/* live threat posture */}
          <div
            className="hidden items-center gap-2 rounded-lg border px-2.5 py-1.5 md:flex"
            style={{ borderColor: `${threatHex}44`, background: `${threatHex}12` }}
            title={`Threat level from the last 5 minutes · updated ${updatedAt ? timeAgo(updatedAt) : 'never'}`}
          >
            <span className="relative flex h-2 w-2">
              <span className="pulse-ring absolute inline-flex h-full w-full rounded-full" style={{ background: threatHex }} />
              <span className="relative inline-flex h-2 w-2 rounded-full" style={{ background: threatHex }} />
            </span>
            <div className="leading-tight">
              <p className="text-[9px] font-semibold uppercase tracking-[0.14em] text-slate-400">Threat level</p>
              <p className="text-[11px] font-bold uppercase" style={{ color: threatHex }}>
                {threatLevel}
              </p>
            </div>
            <div className="border-l border-slate-700/60 pl-2 leading-tight">
              <p className="text-[9px] font-semibold uppercase tracking-[0.14em] text-slate-400">Flows 5m</p>
              <p className="mono text-[11px] text-slate-200">{formatNumber(posture?.flows ?? 0)}</p>
            </div>
          </div>

          {/* websocket state */}
          <span
            className={`badge ${connected ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-300' : 'border-slate-700 bg-slate-800/60 text-slate-400'}`}
            title={connected ? `${formatNumber(messageCount)} live messages received` : `Live stream ${status}`}
          >
            {connected ? <Wifi size={10} /> : <WifiOff size={10} />}
            <span className="hidden sm:inline">{connected ? 'Live' : status === 'connecting' ? 'Connecting' : 'Offline'}</span>
          </span>

          {/* account menu */}
          <div className="relative" ref={menuRef}>
            <button
              type="button"
              onClick={() => setMenuOpen((open) => !open)}
              className="flex items-center gap-2 rounded-lg border border-slate-800 bg-slate-900/70 px-2 py-1.5 text-left transition hover:border-slate-700"
            >
              <span className="flex h-6 w-6 items-center justify-center rounded-md bg-cyan-500/15 text-[10px] font-bold text-cyan-300">
                {String(user?.name || user?.email || '?')
                  .split(/\s+/)
                  .slice(0, 2)
                  .map((part) => part[0]?.toUpperCase())
                  .join('')}
              </span>
              <span className="hidden leading-tight sm:block">
                <span className="block max-w-[120px] truncate text-[11px] font-semibold text-slate-200">{user?.name || 'Analyst'}</span>
                <span className="mono block text-[9px] uppercase tracking-wide text-slate-500">{user?.role}</span>
              </span>
              <ChevronDown size={13} className="text-slate-500" />
            </button>

            {menuOpen ? (
              <div className="animate-in-fast absolute right-0 top-[calc(100%+6px)] w-60 overflow-hidden rounded-xl border border-slate-700/70 bg-slate-900 shadow-2xl">
                <div className="border-b border-slate-800 px-3 py-2.5">
                  <p className="truncate text-xs font-semibold text-slate-100">{user?.name}</p>
                  <p className="mono truncate text-[10px] text-slate-500">{user?.email}</p>
                  <p className="mt-1.5">
                    <span className="badge border-cyan-500/40 bg-cyan-500/10 text-cyan-300">{user?.role}</span>
                  </p>
                </div>
                <div className="p-1">
                  <Link
                    to="/settings"
                    onClick={() => setMenuOpen(false)}
                    className="flex items-center gap-2 rounded-lg px-2.5 py-2 text-xs text-slate-300 transition hover:bg-slate-800 hover:text-white"
                  >
                    <UserCog size={13} /> Profile & system settings
                  </Link>
                  <Link
                    to="/admin"
                    onClick={() => setMenuOpen(false)}
                    className="flex items-center gap-2 rounded-lg px-2.5 py-2 text-xs text-slate-300 transition hover:bg-slate-800 hover:text-white"
                  >
                    <RefreshCw size={13} /> Admin console
                  </Link>
                  <button
                    type="button"
                    onClick={() => {
                      setMenuOpen(false)
                      logout()
                      navigate('/login', { replace: true })
                    }}
                    className="flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-xs text-rose-300 transition hover:bg-rose-500/10"
                  >
                    <LogOut size={13} /> Sign out
                  </button>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </header>
  )
}
