import { useEffect, useMemo, useState } from 'react'
import {
  Activity,
  AlertTriangle,
  Boxes,
  CheckCircle2,
  Database,
  FileText,
  Gauge,
  HardDrive,
  KeyRound,
  Layers,
  Link2,
  Lock,
  Mail,
  Plus,
  Power,
  PowerOff,
  RefreshCw,
  RotateCcw,
  Save,
  ScrollText,
  ServerCog,
  ShieldAlert,
  ShieldCheck,
  Trash2,
  UserCog,
  Users,
  XCircle,
} from 'lucide-react'
import { adminApi, authApi } from '../services/endpoints'
import { useAction, useApi } from '../hooks/useApi'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../context/ToastContext'
import {
  Badge,
  Button,
  Card,
  Checkbox,
  ConfirmDialog,
  DataTable,
  EmptyState,
  ErrorState,
  Field,
  Input,
  KeyValue,
  LoadingState,
  Modal,
  Progress,
  SearchInput,
  Select,
  StatCard,
  StatusBadge,
} from '../components/ui'
import { DonutChart } from '../components/charts/charts'
import { formatDateTime, formatNumber, formatPercent, timeAgo } from '../utils/format'
import { ROLES } from '../utils/constants'
import { ROLE_TONES } from '../utils/theme'

const ROLE_OPTIONS = ROLES.map((role) => ({ value: role.value, label: role.label }))

const SETTING_FIELDS = [
  { key: 'alert_throttle_minutes', label: 'Alert throttle window', unit: 'minutes', type: 'number', min: 0, max: 1440, hint: 'Repeat alerts for the same source/target are suppressed for this long.' },
  { key: 'anomaly_contamination', label: 'Anomaly contamination', unit: 'fraction', type: 'number', step: 0.01, min: 0.005, max: 0.4, hint: 'Expected anomaly share used when training Isolation Forest.' },
  { key: 'simulation_default_rate', label: 'Simulation default intensity', unit: '1–10', type: 'number', min: 1, max: 10, hint: 'Intensity preselected on the Simulation Console.' },
  { key: 'max_forecast_history_rows', label: 'Forecast history retention', unit: 'rows', type: 'number', min: 100, max: 200000, hint: 'Traffic rows considered when building forecast history.' },
  { key: 'seed_traffic_records', label: 'Seed traffic records', unit: 'rows', type: 'number', min: 100, max: 20000, hint: 'Volume generated by the demo seeder on a fresh database.' },
]

export default function Admin() {
  const { user, can } = useAuth()
  const toast = useToast()
  const isAdmin = user?.role === 'admin'

  const stats = useApi(() => adminApi.stats(), [], { keepPrevious: true })
  const health = useApi(() => adminApi.health(), [], { keepPrevious: true })
  const settings = useApi(() => (isAdmin ? adminApi.settings() : Promise.resolve(null)), [], { enabled: isAdmin, keepPrevious: true })
  const seedStatus = useApi(() => adminApi.seedStatus(), [])
  const roles = useApi(() => authApi.roles(), [])

  const refresh = () => {
    stats.refetch()
    health.refetch()
    seedStatus.refetch()
    if (isAdmin) settings.refetch()
  }

  const counts = stats.data?.counts || {}

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">
        <StatCard label="Users" value={formatNumber(counts.users)} icon={Users} tone="cyan" loading={stats.loading && !stats.data} />
        <StatCard label="Traffic records" value={formatNumber(counts.traffic_records)} icon={Layers} tone="green" hint={`${formatNumber(counts.predictions)} predictions`} />
        <StatCard label="Alerts" value={formatNumber(counts.alerts)} icon={ShieldAlert} tone="red" hint={`${formatNumber(stats.data?.alerts?.critical_open)} critical open`} />
        <StatCard label="Models" value={formatNumber(counts.models)} icon={Boxes} tone="purple" hint={`${formatNumber(counts.datasets)} datasets`} />
        <StatCard label="Ledger events" value={formatNumber(counts.blockchain_events)} icon={Lock} tone="amber" hint={`${formatPercent((stats.data?.blockchain?.verified_percentage ?? 0) / 100, 1)} verified`} />
        <StatCard label="Audit entries" value={formatNumber(counts.audit_logs)} icon={ScrollText} tone="blue" hint={`${formatNumber(counts.reports)} reports · ${formatNumber(counts.forecasts)} forecasts`} />
      </div>

      <Card
        title="Component health"
        subtitle="Live backend self-check (API, ML engine, database, Appwrite, blockchain, simulation)"
        icon={Activity}
        actions={
          <div className="flex items-center gap-2">
            {health.data ? <StatusBadge status={health.data.status} /> : null}
            <Button size="sm" variant="ghost" icon={RefreshCw} onClick={refresh} loading={health.loading}>Refresh</Button>
          </div>
        }
      >
        {health.loading && !health.data ? (
          <LoadingState label="Running health checks…" />
        ) : health.error ? (
          <ErrorState error={health.error} onRetry={health.refetch} compact />
        ) : (
          <div className="grid gap-2.5 sm:grid-cols-2 xl:grid-cols-3">
            {Object.entries(health.data?.components || {}).map(([name, component]) => (
              <div key={name} className="rounded-xl border border-slate-800 bg-slate-950/40 p-3">
                <div className="flex items-center justify-between gap-2">
                  <p className="text-[11.5px] font-semibold capitalize text-slate-200">{name.replace(/_/g, ' ')}</p>
                  <StatusBadge status={component.status || (component.ok ? 'online' : 'offline')} />
                </div>
                <ul className="mt-1.5 space-y-0.5">
                  {Object.entries(component)
                    .filter(([key, value]) => !['status', 'ok', 'component', 'state', 'counts'].includes(key) && value !== null && value !== undefined && typeof value !== 'object')
                    .slice(0, 6)
                    .map(([key, value]) => (
                      <li key={key} className="flex items-baseline justify-between gap-2">
                        <span className="muted capitalize">{key.replace(/_/g, ' ')}</span>
                        <span className="mono truncate text-[10.5px] text-slate-300">{formatHealthValue(value)}</span>
                      </li>
                    ))}
                </ul>
                {component.detail ? <p className="muted mt-1.5">{component.detail}</p> : null}
                {component.latency_ms !== undefined ? (
                  <p className="mono mt-1 text-[10px] text-slate-500">checked in {Number(component.latency_ms).toFixed(1)} ms</p>
                ) : null}
              </div>
            ))}
          </div>
        )}
      </Card>

      <UsersPanel canManage={can('users.manage')} currentUserId={user?.id} onChanged={() => { stats.refetch() }} />

      {isAdmin ? (
        <SettingsPanel settings={settings} onChanged={refresh} />
      ) : (
        <Card title="Runtime configuration" icon={ServerCog}>
          <EmptyState icon={ServerCog} title="Administrator access required" message="Runtime settings, seeding and demo reset are restricted to the admin role." />
        </Card>
      )}

      <div className="grid gap-4 xl:grid-cols-3">
        <DistributionCard
          title="Alerts by severity"
          icon={ShieldAlert}
          data={stats.data?.alerts?.by_severity}
          loading={stats.loading}
          error={stats.error}
          onRetry={stats.refetch}
        />
        <DistributionCard
          title="Alerts by status"
          icon={AlertTriangle}
          data={stats.data?.alerts?.by_status}
          loading={stats.loading}
          error={stats.error}
          onRetry={stats.refetch}
        />
        <DistributionCard
          title="Ledger events by type"
          icon={Lock}
          data={stats.data?.blockchain?.by_event_type}
          loading={stats.loading}
          error={stats.error}
          onRetry={stats.refetch}
        />
      </div>

      <div className="grid gap-4 xl:grid-cols-2">
        <Card title="Alerts by attack type" subtitle="Lifetime totals across stored alerts" icon={ShieldAlert} dense>
          {Object.keys(stats.data?.alerts?.by_attack_type || {}).length ? (
            <ul className="space-y-1.5">
              {Object.entries(stats.data.alerts.by_attack_type)
                .sort((a, b) => b[1] - a[1])
                .map(([type, value]) => (
                  <li key={type} className="flex items-center gap-2">
                    <span className="w-32 shrink-0 truncate text-[11px] text-slate-300">{type}</span>
                    <Progress className="flex-1" value={value} max={Math.max(...Object.values(stats.data.alerts.by_attack_type))} tone="red" />
                    <span className="mono w-12 shrink-0 text-right text-[10.5px] text-slate-400">{formatNumber(value)}</span>
                  </li>
                ))}
            </ul>
          ) : (
            <EmptyState icon={ShieldAlert} title="No alerts recorded" message="Alerts appear once traffic is analyzed." />
          )}
        </Card>

        <Card title="Audit entries by category" subtitle="Privileged action coverage" icon={ScrollText} dense>
          {Object.keys(stats.data?.audit?.by_category || {}).length ? (
            <ul className="space-y-1.5">
              {Object.entries(stats.data.audit.by_category)
                .sort((a, b) => b[1] - a[1])
                .map(([category, value]) => (
                  <li key={category} className="flex items-center gap-2">
                    <span className="w-32 shrink-0 truncate text-[11px] text-slate-300">{category}</span>
                    <Progress className="flex-1" value={value} max={Math.max(...Object.values(stats.data.audit.by_category))} tone="cyan" />
                    <span className="mono w-12 shrink-0 text-right text-[10.5px] text-slate-400">{formatNumber(value)}</span>
                  </li>
                ))}
            </ul>
          ) : (
            <EmptyState icon={ScrollText} title="No audit entries" message="Entries appear as actions are performed." />
          )}
        </Card>
      </div>

      <Card
        title="Role & permission matrix"
        subtitle="Server-side authorization map — the UI hides controls, the API enforces them"
        icon={ShieldCheck}
        actions={<Button size="sm" variant="ghost" icon={RefreshCw} onClick={roles.refetch} loading={roles.loading}>Refresh</Button>}
      >
        {roles.loading && !roles.data ? (
          <LoadingState label="Loading permission matrix…" />
        ) : roles.error ? (
          <ErrorState error={roles.error} onRetry={roles.refetch} compact />
        ) : (
          <div className="space-y-3">
            <div className="grid gap-2.5 sm:grid-cols-3">
              {(roles.data?.roles || []).map((role) => (
                <div key={role.key} className="rounded-xl border border-slate-800 bg-slate-950/40 p-3">
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-[11.5px] font-semibold text-slate-200">{role.label}</p>
                    <Badge tone={ROLE_TONES[role.key] || 'slate'}>{role.key}</Badge>
                  </div>
                  <p className="muted mt-1">{role.description}</p>
                  <p className="mono mt-1.5 text-[10px] text-slate-500">{role.capabilities?.length || 0} capabilities</p>
                </div>
              ))}
            </div>
            <div className="overflow-x-auto">
              <table className="table">
                <thead>
                  <tr>
                    <th>Permission</th>
                    {(roles.data?.roles || []).map((role) => <th key={role.key} className="text-center">{role.label}</th>)}
                  </tr>
                </thead>
                <tbody>
                  {Object.entries(roles.data?.permission_matrix || {}).map(([permission, allowed]) => (
                    <tr key={permission}>
                      <td className="mono text-[10.5px] text-slate-300">{permission}</td>
                      {(roles.data?.roles || []).map((role) => (
                        <td key={role.key} className="text-center">
                          {(allowed || []).includes(role.key) ? (
                            <CheckCircle2 size={12} className="mx-auto text-emerald-400" />
                          ) : (
                            <span className="text-slate-700">—</span>
                          )}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </Card>

      {isAdmin ? <DataLifecyclePanel seedStatus={seedStatus} onChanged={refresh} /> : null}
    </div>
  )
}

function UsersPanel({ canManage, currentUserId, onChanged }) {
  const toast = useToast()
  const [search, setSearch] = useState('')
  const [page, setPage] = useState({ limit: 25, offset: 0, page: 1 })
  const [createOpen, setCreateOpen] = useState(false)
  const [createForm, setCreateForm] = useState({ name: '', email: '', password: '', role: 'analyst' })
  const [pendingDelete, setPendingDelete] = useState(null)
  const [resetLink, setResetLink] = useState(null)

  const users = useApi(
    () => (canManage ? adminApi.users({ limit: page.limit, offset: page.offset, search: search || undefined }) : Promise.resolve(null)),
    [page.limit, page.offset, search],
    { enabled: canManage, keepPrevious: true },
  )

  const update = useAction(
    async (userId, payload, message) => {
      const result = await adminApi.updateUser(userId, payload)
      toast.success('User updated', message)
      users.refetch()
      onChanged?.()
      return result
    },
    { onError: (failure) => toast.error('Update failed', failure.message) },
  )

  const remove = useAction(
    async (userId) => {
      await adminApi.deleteUser(userId)
      toast.success('User deleted', 'The account was removed; historical audit entries are preserved.')
      setPendingDelete(null)
      users.refetch()
      onChanged?.()
    },
    { onError: (failure) => toast.error('Delete failed', failure.message) },
  )

  const create = useAction(
    async () => {
      const result = await adminApi.createUser(createForm)
      toast.success('User created', `${result.email} was created with the ${result.role} role.`)
      setCreateOpen(false)
      setCreateForm({ name: '', email: '', password: '', role: 'analyst' })
      users.refetch()
      onChanged?.()
      return result
    },
    { onError: (failure) => toast.error('Could not create user', failure.message) },
  )

  const issueReset = useAction(
    async (email) => {
      const result = await authApi.forgotPassword(email)
      setResetLink(result)
      if (result.dev_token) {
        toast.success('Reset link issued', `Token valid for ${result.expires_in_minutes} minutes (returned directly because no mail provider is configured).`)
      } else {
        toast.info('Reset requested', result.message || 'If the account exists, a reset link has been issued.')
      }
      return result
    },
    { onError: (failure) => toast.error('Could not issue reset', failure.message) },
  )

  if (!canManage) {
    return (
      <Card title="User management" icon={Users}>
        <EmptyState icon={Users} title="Administrator access required" message="Only users with the users.manage capability can administer accounts." />
      </Card>
    )
  }

  return (
    <Card
      title="User management"
      subtitle={`${formatNumber(users.data?.pagination?.total ?? 0)} accounts · roles are enforced server side on every request`}
      icon={Users}
      bodyClass="p-0"
      actions={
        <div className="flex items-center gap-2">
          <SearchInput className="w-44" value={search} onChange={(value) => { setPage({ limit: page.limit, offset: 0, page: 1 }); setSearch(value) }} placeholder="Search name or email…" />
          <Button size="sm" variant="primary" icon={Plus} onClick={() => setCreateOpen(true)}>New user</Button>
        </div>
      }
    >
      <DataTable
        columns={[
          { key: 'name', header: 'Account', render: (row) => (
            <span className="flex items-center gap-2">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg text-[10px] font-black text-slate-950" style={{ background: row.avatar_color || '#22d3ee' }}>
                {(row.name || row.email || '?').slice(0, 2).toUpperCase()}
              </span>
              <span className="block min-w-0">
                <span className="flex items-center gap-1.5">
                  <span className="truncate text-[11.5px] font-medium text-slate-200">{row.name || '—'}</span>
                  {row.id === currentUserId ? <Badge tone="cyan">you</Badge> : null}
                </span>
                <span className="mono block truncate text-[10px] text-slate-500">{row.email}</span>
              </span>
            </span>
          ) },
          { key: 'role', header: 'Role', width: '168px', render: (row) => (
            row.id === currentUserId ? (
              <Badge tone={ROLE_TONES[row.role] || 'slate'}>{row.role}</Badge>
            ) : (
              <select
                className="select py-1 text-[11px]"
                value={row.role}
                disabled={update.busy}
                onChange={(event) => update.run(row.id, { role: event.target.value }, `${row.email} is now ${event.target.value}.`)}
              >
                {ROLE_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}
              </select>
            )
          ) },
          { key: 'is_active', header: 'Status', width: '132px', render: (row) => (
            row.id === currentUserId ? (
              <StatusBadge status="online" label="active (you)" />
            ) : (
              <Button
                size="xs"
                variant={row.is_active ? 'ghost' : 'success'}
                icon={row.is_active ? <PowerOff size={11} /> : <Power size={11} />}
                loading={update.busy}
                onClick={() => update.run(row.id, { is_active: !row.is_active }, row.is_active ? `${row.email} was disabled.` : `${row.email} was re-enabled.`)}
              >
                {row.is_active ? 'Disable' : 'Enable'}
              </Button>
            )
          ) },
          { key: 'mfa_enabled', header: 'MFA', width: '78px', render: (row) => (
            row.mfa_enabled ? <Badge tone="green"><ShieldCheck size={9} /> on</Badge> : <Badge tone="slate">off</Badge>
          ) },
          { key: 'auth_provider', header: 'Provider', width: '104px', hideBelow: 'lg:table-cell', render: (row) => <Badge tone={row.auth_provider === 'appwrite' ? 'purple' : 'cyan'}>{row.auth_provider}</Badge> },
          { key: 'capabilities', header: 'Capabilities', width: '108px', hideBelow: 'xl:table-cell', render: (row) => <span className="mono text-[10.5px] text-slate-400">{row.capabilities?.length || 0} granted</span> },
          { key: 'last_login', header: 'Last sign-in', width: '124px', sortable: true, render: (row) => <span className="mono text-[10.5px] text-slate-400" title={formatDateTime(row.last_login)}>{row.last_login ? timeAgo(row.last_login) : 'never'}</span> },
          { key: 'created_at', header: 'Created', width: '124px', hideBelow: 'lg:table-cell', sortable: true, render: (row) => <span className="mono text-[10.5px] text-slate-400" title={formatDateTime(row.created_at)}>{timeAgo(row.created_at)}</span> },
          { key: 'actions', header: '', width: '140px', align: 'right', render: (row) => (
            <span className="flex items-center justify-end gap-1">
              <Button size="xs" variant="secondary" icon={KeyRound} loading={issueReset.busy} onClick={() => issueReset.run(row.email)} title="Issue a password reset link">Reset</Button>
              <Button size="xs" variant="danger" icon={Trash2} disabled={row.id === currentUserId} title={row.id === currentUserId ? 'You cannot delete your own account' : 'Delete account'} onClick={() => setPendingDelete(row)} />
            </span>
          ) },
        ]}
        rows={users.data?.items || []}
        loading={users.loading}
        error={users.error}
        onRetry={users.refetch}
        pagination={users.data?.pagination}
        onPageChange={setPage}
        empty={<EmptyState icon={Users} title="No accounts match" message="Clear the search or create a new user." />}
      />

      {issueReset.result ? (
        <div className="border-t border-slate-800 p-3">
          <div className="rounded-xl border border-amber-500/30 bg-amber-500/8 p-3">
            <p className="flex items-center gap-1.5 text-xs font-semibold text-amber-200">
              <Mail size={13} /> Password reset issued
            </p>
            <p className="muted mt-1">{issueReset.result.message}</p>
            {issueReset.result.dev_token ? (
              <div className="mt-2 space-y-1.5">
                <p className="mono break-all rounded-lg border border-slate-700/70 bg-slate-950/60 p-2 text-[10.5px] text-amber-200">
                  {`${window.location.origin}/reset-password?token=${issueReset.result.dev_token}`}
                </p>
                <p className="muted">
                  {issueReset.result.dev_note} Valid for {issueReset.result.expires_in_minutes} minutes. Share it over a secure channel and have the user set a new password immediately.
                </p>
                <div className="flex gap-2">
                  <Button
                    size="xs"
                    variant="secondary"
                    onClick={async () => {
                      try {
                        await navigator.clipboard.writeText(`${window.location.origin}/reset-password?token=${issueReset.result.dev_token}`)
                        toast.success('Copied', 'Reset link copied to the clipboard.')
                      } catch {
                        toast.error('Copy failed', 'Select the link text manually.')
                      }
                    }}
                  >
                    Copy link
                  </Button>
                  <Button size="xs" variant="ghost" onClick={() => setResetLink(null)}>Dismiss</Button>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      ) : null}

      <Modal
        open={createOpen}
        onClose={() => setCreateOpen(false)}
        title="Create an account"
        subtitle="The user signs in with these credentials immediately"
        icon={UserCog}
        footer={
          <>
            <Button variant="ghost" onClick={() => setCreateOpen(false)}>Cancel</Button>
            <Button
              variant="primary"
              icon={Plus}
              loading={create.busy}
              disabled={!createForm.name.trim() || !createForm.email.trim() || createForm.password.length < 8}
              onClick={create.run}
            >
              Create user
            </Button>
          </>
        }
      >
        <div className="space-y-3">
          <Input label="Full name" value={createForm.name} onChange={(event) => setCreateForm({ ...createForm, name: event.target.value })} placeholder="Analyst name" required />
          <Input label="Work email" type="email" value={createForm.email} onChange={(event) => setCreateForm({ ...createForm, email: event.target.value })} placeholder="analyst@organisation.in" required />
          <Input
            label="Temporary password"
            type="text"
            value={createForm.password}
            onChange={(event) => setCreateForm({ ...createForm, password: event.target.value })}
            placeholder="At least 8 characters"
            required
            error={createForm.password && createForm.password.length < 8 ? 'Use at least 8 characters' : null}
            hint="Share it securely; the user should change it from the Settings page after signing in."
          />
          <Select label="Role" value={createForm.role} onChange={(event) => setCreateForm({ ...createForm, role: event.target.value })} options={ROLE_OPTIONS} hint={ROLES.find((role) => role.value === createForm.role)?.description} />
          {create.error ? <ErrorState error={create.error} compact /> : null}
        </div>
      </Modal>

      <ConfirmDialog
        open={Boolean(pendingDelete)}
        onClose={() => setPendingDelete(null)}
        onConfirm={() => remove.run(pendingDelete.id)}
        busy={remove.busy}
        title="Delete this account?"
        confirmLabel="Delete user"
        tone="danger"
        message={`${pendingDelete?.email} will be removed. Their audit history and any records they created are kept for accountability.`}
      />
    </Card>
  )
}

function SettingsPanel({ settings, onChanged }) {
  const toast = useToast()
  const [form, setForm] = useState({})

  useEffect(() => {
    if (settings.data?.runtime) setForm({ ...settings.data.runtime })
  }, [settings.data])

  const save = useAction(
    async () => {
      const runtime = settings.data?.runtime || {}
      const payload = {}
      Object.keys(form).forEach((key) => {
        const value = form[key]
        if (value === '' || value === null || value === undefined) return
        if (typeof runtime[key] === 'boolean') payload[key] = Boolean(value)
        else if (typeof runtime[key] === 'number') payload[key] = Number(value)
      })
      if (!Object.keys(payload).length) throw new Error('Nothing to save — no runtime value has changed.')
      const result = await adminApi.updateSettings(payload)
      const changed = Object.keys(result?.changed || {})
      toast.success(
        changed.length ? 'Settings updated' : 'No changes applied',
        changed.length ? `${changed.join(', ')} now take effect immediately.` : 'The submitted values already match the running configuration.',
      )
      settings.refetch()
      onChanged?.()
      return result
    },
    { onError: (failure) => toast.error('Could not save settings', failure.message) },
  )

  const runtime = settings.data?.runtime || {}
  const defaults = settings.data?.defaults || {}
  const environment = settings.data?.environment || {}
  const security = settings.data?.security || {}

  const dirty = useMemo(
    () => Object.keys(form).some((key) => String(form[key]) !== String(runtime[key] ?? '')),
    [form, runtime],
  )

  return (
    <div className="grid gap-4 xl:grid-cols-2">
      <Card
        title="Runtime configuration"
        subtitle="Applied to the running process; persist them in .env to survive a restart"
        icon={ServerCog}
        actions={
          <div className="flex items-center gap-2">
            {dirty ? <Badge tone="amber">unsaved changes</Badge> : null}
            <Button size="sm" variant="ghost" icon={RotateCcw} onClick={() => setForm({ ...runtime })} disabled={!dirty}>Discard</Button>
            <Button size="sm" variant="primary" icon={Save} loading={save.busy} disabled={!dirty} onClick={save.run}>Save</Button>
          </div>
        }
      >
        {settings.loading && !settings.data ? (
          <LoadingState label="Loading runtime settings…" />
        ) : settings.error ? (
          <ErrorState error={settings.error} onRetry={settings.refetch} compact />
        ) : (
          <div className="space-y-3">
            {SETTING_FIELDS.map((field) => (
              <div key={field.key} className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_140px] sm:items-center">
                <div>
                  <p className="text-[11.5px] font-medium text-slate-200">{field.label}</p>
                  <p className="muted">{field.hint}</p>
                  <p className="mono mt-0.5 text-[10px] text-slate-500">
                    {field.key} · default {String(defaults[field.key] ?? '—')}
                    {String(form[field.key] ?? '') !== String(runtime[field.key] ?? '') ? ` · running ${String(runtime[field.key] ?? '—')}` : ''}
                  </p>
                </div>
                <input
                  className="input mono text-right"
                  type={field.type}
                  step={field.step}
                  min={field.min}
                  max={field.max}
                  value={form[field.key] ?? ''}
                  onChange={(event) => setForm({ ...form, [field.key]: event.target.value })}
                />
              </div>
            ))}

            <div className="flex items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-950/40 p-3">
              <div>
                <p className="text-[11.5px] font-medium text-slate-200">Simulation autostart</p>
                <p className="muted">Begin a synthetic run automatically when the backend boots (useful for demos).</p>
              </div>
              <Checkbox
                checked={Boolean(form.simulation_autostart)}
                onChange={(value) => setForm({ ...form, simulation_autostart: value })}
                label={form.simulation_autostart ? 'enabled' : 'disabled'}
              />
            </div>

            {save.error ? <ErrorState error={save.error} compact /> : null}
            {save.result?.changed && Object.keys(save.result.changed).length ? (
              <ul className="space-y-1">
                {Object.entries(save.result.changed).map(([key, change]) => (
                  <li key={key} className="mono flex items-center gap-2 rounded-lg border border-emerald-500/25 bg-emerald-500/8 px-2.5 py-1.5 text-[10.5px] text-emerald-200">
                    <CheckCircle2 size={11} /> {key}: {String(change.from)} → {String(change.to)}
                  </li>
                ))}
              </ul>
            ) : null}
          </div>
        )}
      </Card>

      <div className="space-y-4">
        <Card title="Environment" subtitle="From the backend configuration (read-only)" icon={Gauge} dense>
          <KeyValue
            columns={2}
            items={[
              { label: 'Application', value: environment.app_name },
              { label: 'Version', value: environment.version, mono: true },
              { label: 'Environment', value: environment.environment },
              { label: 'Storage backend', value: String(environment.storage_backend).toUpperCase() },
              { label: 'Appwrite', value: environment.appwrite_enabled ? 'enabled' : 'disabled' },
              { label: 'Blockchain mode', value: environment.blockchain_mode },
              { label: 'Chain id', value: environment.blockchain_chain_id ?? 'not configured', mono: true },
              { label: 'Contract', value: environment.blockchain_contract_address ?? 'not deployed', mono: true },
              { label: 'Simulation', value: environment.simulation_enabled ? 'enabled' : 'disabled' },
              { label: 'Default classifier', value: environment.default_classifier, mono: true },
              { label: 'Upload limit', value: `${environment.max_upload_mb} MB` },
              { label: 'Allowed extensions', value: (environment.allowed_upload_extensions || []).join(', '), mono: true },
            ]}
          />
        </Card>

        <Card title="Security posture" subtitle="Authentication, tokens and rate limiting" icon={Lock} dense>
          <KeyValue
            columns={2}
            items={[
              { label: 'JWT algorithm', value: security.jwt_algorithm, mono: true },
              { label: 'Access token lifetime', value: `${security.access_token_minutes} minutes`, mono: true },
              { label: 'Reset token lifetime', value: `${security.reset_token_minutes} minutes`, mono: true },
              { label: 'Global rate limit', value: security.rate_limit, mono: true },
              { label: 'Auth rate limit', value: security.auth_rate_limit, mono: true },
              { label: 'CORS allow-all', value: security.cors_allow_all ? 'yes (development)' : 'no' },
              { label: 'CORS origins', value: (security.cors_origins || []).join(', ') || '—', mono: true },
              { label: 'Upload limit', value: `${security.max_upload_mb} MB`, mono: true },
            ]}
          />
          {security.cors_allow_all ? (
            <p className="muted mt-2 flex items-start gap-1.5 rounded-lg border border-amber-500/25 bg-amber-500/8 px-2.5 py-2">
              <AlertTriangle size={11} className="mt-0.5 shrink-0 text-amber-300" />
              CORS is wide open for local development. Set <span className="mono">CORS_ORIGINS</span> to your production frontend origin before deploying.
            </p>
          ) : null}
        </Card>
      </div>
    </div>
  )
}

function DataLifecyclePanel({ seedStatus, onChanged }) {
  const toast = useToast()
  const [seedOptions, setSeedOptions] = useState({ force: false, traffic_records: 1800 })
  const [resetOpen, setResetOpen] = useState(false)

  const seed = useAction(
    async () => {
      const result = await adminApi.reseed({
        force: seedOptions.force,
        traffic_records: seedOptions.force ? Number(seedOptions.traffic_records) : undefined,
      })
      toast.success('Seeding finished', `Status: ${result?.status || 'unknown'} — ${(result?.steps || []).filter((step) => step.ok).length}/${(result?.steps || []).length} steps succeeded.`)
      seedStatus.refetch()
      onChanged?.()
      return result
    },
    { onError: (failure) => toast.error('Seeding failed', failure.message) },
  )

  const resetDemo = useAction(
    async () => {
      const result = await adminApi.resetDemo()
      toast.success('Demo data rebuilt', `Cleared ${Object.entries(result?.cleared || {}).map(([key, value]) => `${value} ${key}`).join(', ') || 'operational data'}.`)
      setResetOpen(false)
      seedStatus.refetch()
      onChanged?.()
      return result
    },
    { onError: (failure) => toast.error('Reset failed', failure.message) },
  )

  return (
    <Card title="Data lifecycle" subtitle="Bootstrap and reset the demonstration dataset" icon={Database}>
      <div className="grid gap-4 lg:grid-cols-2">
        <div className="space-y-3">
          <p className="panel-title flex items-center gap-1.5"><HardDrive size={11} /> Seed platform data</p>
          <p className="muted">
            Creates the three role accounts, trains and activates a classifier plus anomaly detector, generates labelled traffic through the normal pipeline,
            runs a forecast and writes the ledger genesis entry. Every step is idempotent.
          </p>
          <div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end">
            <Input
              label="Traffic records to generate"
              type="number"
              min={100}
              max={20000}
              value={seedOptions.traffic_records}
              onChange={(event) => setSeedOptions({ ...seedOptions, traffic_records: event.target.value })}
              hint="100 – 20,000 · only used with force"
            />
            <Checkbox checked={seedOptions.force} onChange={(value) => setSeedOptions({ ...seedOptions, force: value })} label="Force (rebuild even if data exists)" />
          </div>
          <Button variant="primary" icon={RefreshCw} loading={seed.busy} onClick={seed.run}>Run seeder</Button>
          {seed.error ? <ErrorState error={seed.error} compact /> : null}
          {seed.result ? (
            <ul className="space-y-1">
              {(seed.result.steps || []).map((step) => (
                <li key={step.step} className="flex items-center gap-2 text-[11px]">
                  {step.ok ? <CheckCircle2 size={11} className="text-emerald-400" /> : <XCircle size={11} className="text-rose-400" />}
                  <span className="mono text-slate-300">{step.step}</span>
                  <span className="muted truncate">{step.detail}</span>
                  <span className="mono ml-auto text-slate-500">{Number(step.seconds || 0).toFixed(2)}s</span>
                </li>
              ))}
            </ul>
          ) : null}

          <div className="rounded-xl border border-rose-500/30 bg-rose-500/6 p-3">
            <p className="flex items-center gap-1.5 text-xs font-semibold text-rose-200"><Trash2 size={13} /> Destructive reset</p>
            <p className="muted mt-1">
              Deletes traffic records, predictions, forecasts and alerts, then re-seeds from scratch. Users, datasets, models and the integrity ledger are preserved.
            </p>
            <Button className="mt-2" variant="danger" icon={RotateCcw} onClick={() => setResetOpen(true)}>Reset demo data…</Button>
          </div>
        </div>

        <div>
          <p className="panel-title mb-2 flex items-center gap-1.5"><ScrollText size={11} /> Last seeding run</p>
          {seedStatus.loading && !seedStatus.data ? (
            <LoadingState label="Loading seed status…" />
          ) : seedStatus.error ? (
            <ErrorState error={seedStatus.error} onRetry={seedStatus.refetch} compact />
          ) : (
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <StatusBadge status={seedStatus.data?.status === 'complete' ? 'online' : seedStatus.data?.status === 'error' ? 'offline' : 'degraded'} label={seedStatus.data?.status || 'unknown'} />
                {seedStatus.data?.finished_at ? <span className="muted">{timeAgo(seedStatus.data.finished_at)}</span> : null}
                {seedStatus.data?.seconds !== undefined ? <span className="mono ml-auto text-[10.5px] text-slate-500">{Number(seedStatus.data.seconds).toFixed(2)}s total</span> : null}
              </div>
              {seedStatus.data?.error ? (
                <p className="rounded-lg border border-rose-500/30 bg-rose-500/8 px-2.5 py-2 text-[11px] text-rose-200">{seedStatus.data.error}</p>
              ) : null}
              <ul className="space-y-1">
                {(seedStatus.data?.steps || []).map((step) => (
                  <li key={step.step} className="flex items-center gap-2 text-[11px]">
                    {step.ok ? <CheckCircle2 size={11} className="text-emerald-400" /> : <XCircle size={11} className="text-rose-400" />}
                    <span className="mono text-slate-300">{step.step}</span>
                    <span className="muted truncate">{step.detail}</span>
                    {step.at ? <span className="mono ml-auto shrink-0 text-slate-500">{timeAgo(step.at)}</span> : null}
                  </li>
                ))}
              </ul>
              <Button size="sm" variant="ghost" icon={RefreshCw} onClick={seedStatus.refetch} loading={seedStatus.loading}>Refresh status</Button>
            </div>
          )}
        </div>
      </div>

      <ConfirmDialog
        open={resetOpen}
        onClose={() => setResetOpen(false)}
        onConfirm={resetDemo.run}
        busy={resetDemo.busy}
        title="Reset all demo data?"
        confirmLabel="Delete and re-seed"
        tone="danger"
        message="Traffic records, predictions, forecasts and alerts will be deleted and regenerated. This cannot be undone."
      />
    </Card>
  )
}

function DistributionCard({ title, icon: Icon, data, loading, error, onRetry }) {
  const entries = Object.entries(data || {}).filter(([, value]) => Number(value) > 0)
  return (
    <Card title={title} icon={Icon} dense>
      {loading && !data ? (
        <LoadingState label="Loading statistics…" />
      ) : error ? (
        <ErrorState error={error} onRetry={onRetry} compact />
      ) : entries.length ? (
        <>
          <DonutChart data={entries.map(([name, value]) => ({ name, value }))} height={170} formatter={(value) => formatNumber(value)} />
          <ul className="mt-2 space-y-1">
            {entries.sort((a, b) => b[1] - a[1]).map(([name, value]) => (
              <li key={name} className="flex items-center gap-2 text-[11px]">
                <span className="mono flex-1 truncate text-slate-300">{name}</span>
                <span className="mono text-slate-400">{formatNumber(value)}</span>
              </li>
            ))}
          </ul>
        </>
      ) : (
        <EmptyState icon={Icon} title="No data yet" message="Statistics appear once the platform records activity." />
      )}
    </Card>
  )
}

function formatHealthValue(value) {
  if (typeof value === 'boolean') return value ? 'yes' : 'no'
  if (typeof value === 'number') return Number.isInteger(value) ? formatNumber(value) : value.toFixed(3)
  return String(value)
}
